#!/bin/sh

case "$1" in
	start)
		echo "Starting aesdsocket"
		start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
		;;
	stop)
		echo "Stopping aesdsocket"
		start-stop-daemon -K -n aesdsocket
		;;
	*)
		start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
	    ;;
esac

exit 0
